### PR TITLE
Medical update!

### PR DESCRIPTION
**Pull request by thingpony**
Let's try this again!

### CODE REVIEW

**Comment by Brimcon** [comment]
Its missing the Ceiling tiles on Deck 3 to cover the new Medical Areas. That may be the source of the Conflicts.

**Comment by thingpony** [comment]
Ceiling tiles added!

**Review by Brimcon — APPROVED** [review]

**Review by TalkingCactus — CHANGES_REQUESTED** [review]
map files need to be in tgm format

**Review by Brimcon — APPROVED** [review]
TGM Confirmed, Merge away

**Review by TalkingCactus — APPROVED** [review]

**Pull request merged**
