### PR TITLE
Map fixes

### PR DESCRIPTION
**Pull request by thingpony**
- Pretty important one, replaces the airless floor tiles in the maint next to the bluesheild office with aired ones.
- Adds a door to the bar
- Makes the circut office better
- Adds a missing railing
- Also adds size guns to the kink vendor

### CODE REVIEW

**Comment by TalkingCactus** [comment]
medbay clothing room needs a medical maintenance airlock

**Comment by TalkingCactus** [comment]
the public EVA room could use a glass airlock maybe with windows too, so people know it's public

**Comment by TalkingCactus** [comment]
can you also patch up the missing camera locations that i posted a few days ago?

**Comment by TalkingCactus** [comment]
pool sauna thing needs a maintenance door too

**Comment by thingpony** [comment]
Didn't even know you had commented, thank you email for not telling me. I can easily get those

**Review by DameonOwen — APPROVED** [review]

**Pull request merged**
