### PR TITLE
Fixes the bar sign facing the wrong way

### PR DESCRIPTION
**Pull request by thingpony**
Also adds telepathy to my teppi and fixs room 14's posters

### CODE REVIEW

**Comment by DameonOwen** [comment]
Giving Hazel that move might not work in the way that you think. If you've tested this and it works, let me know and I will approve. The proc might be limited to pokemon.

**Comment by DameonOwen** [comment]
Also the integration test failures are my fault and should be fixed in the upstream merge PR

**Comment by thingpony** [comment]
https://gyazo.com/9b17889fac9924ced5858eb38cf200ca

It works! But no, sense in merging this one, since map was updated and touched the bar. So I'll just push Hazel's thing on my current PR and close this one in the morning probs

**Comment by DameonOwen** [comment]
Can this be closed?

**Pull request closed without merging**
