### PR TITLE
Fixes Virology Dishes being empty.

### PR DESCRIPTION
**Pull request by Brimcon**
Maybe. Six random Virus Dishes placed in Virology.

### CODE REVIEW

**Comment by TalkingCactus** [comment]
you got this

**Comment by Brimcon** [comment]
Not sure whats conflicting though. Everything works fine on my end.

**Comment by TalkingCactus** [comment]
use tortoise git to clear the conflict then

**Comment by Brimcon** [comment]
File is corrupted on my end. Fuck.

**Comment by TalkingCactus** [comment]
do it betterer this time

**Comment by Brimcon** [comment]
I was hoping to put more than 2 Scrubbers and vents, but Github wasn't happy.

**Pull request merged**
