### PR TITLE
Event update

### PR DESCRIPTION
**Pull request by thingpony**
Disables the PDA spam event
Changes the sound for the Aurora event, and changes it from Nanotrasen to ARFS.

### CODE REVIEW

**Comment by TalkingCactus** [comment]
I think these should be overwrites in the content_arfs directory so they aren't overwritten later

**Comment by thingpony** [comment]
Probably, but I"m not sure how to do that

**Comment by DameonOwen** [comment]
There might not be a way to do that.

**Comment by TalkingCactus** [comment]
simply redefine these changed datums in a new file within the content_arfs folder

**Comment by DameonOwen** [comment]
That'd probably work, yeah.

**Comment by thingpony** [comment]
Alright! I'll try to do that then

**Pull request closed without merging**
